"""init auth service tables

Revision ID: b6adf653272d
Revises: 
Create Date: 2025-11-02 17:45:41.294729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6adf653272d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_auth_id'), 'auth', ['id'], unique=False)
    op.create_table('auth_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_index(op.f('ix_auth_type_id'), 'auth_type', ['id'], unique=False)
    op.create_table('auth_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_account_id', sa.Integer(), nullable=False),
    sa.Column('auth_type_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.Enum('GOOGLE', 'APPLE', 'FACEBOOK', 'EMAIL', 'PHONE', name='providertype'), nullable=False),
    sa.Column('auth_identifier', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auth_account_id'], ['auth.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['auth_type_id'], ['auth_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_identifier', 'provider_type', name='uq_auth_identifier_provider')
    )
    op.create_index(op.f('ix_auth_data_id'), 'auth_data', ['id'], unique=False)
    op.create_table('session_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'PASSWORD_CHANGE', name='sessionaction'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_audit_id'), 'session_audit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_audit_id'), table_name='session_audit')
    op.drop_table('session_audit')
    op.drop_index(op.f('ix_auth_data_id'), table_name='auth_data')
    op.drop_table('auth_data')
    op.drop_index(op.f('ix_auth_type_id'), table_name='auth_type')
    op.drop_table('auth_type')
    op.drop_index(op.f('ix_auth_id'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
